instance of OsConfigResource as $OsConfigResource0ref
{
    ResourceID = "machine-detection";
    PayloadKey = "machine-detection";
    RuleId = "machine-detection";
    ComponentName = "SecurityBaseline";
    InitObjectName = "machine-detection";
    ReportedObjectName = "machine-detection";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "machine-detection";
    DesiredObjectValue = "xxx";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "MachineDetection";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OMI_ConfigurationDocument
{
    Version="2.0.0";
    CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
    Author="Microsoft";
    GenerationDate="10/16/2024 16:38:00 PST";
    Name="OsConfigSshServerSecurity";
};