name: Fuzzer execution

on:
  workflow_dispatch:
  pull_request:
  # schedule:
    # - cron: '0 20 * * *' # Every day at 12pm PST (UTC-8)

jobs:
  fuzzer-execution:
    name: Fuzzer execution matrix
    uses: ./.github/workflows/fuzzing-run.yml
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            { os: ubuntu, version: 22.04, package-type: DEB },
          ]
        arch: [amd64]
    with:
      target: ${{ matrix.target.os }}-${{ matrix.target.version }}
      arch: ${{ matrix.arch }}
      package-type: ${{ matrix.target.package-type }}