name: Fuzzer execution

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      arch:
        required: true
        type: string
      package-type:
        required: true
        type: string

jobs:
  package:
    uses: ./.github/workflows/package-build.yml
    with:
      target: ${{ inputs.target }}
      arch: ${{ inputs.arch }}
      artifact: ${{ inputs.target }}-fuzzer
      package-type: ${{ inputs.package-type }}
      build-fuzzers: true

  fuzzer-execution:
    needs: package
    runs-on: [self-hosted, 1ES.Pool=e2e-pool, '1ES.ImageOverride=${{ inputs.target }}']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        id: download
        with:
          name: ${{ inputs.target }}-fuzzer

      - name: Run osconfig-fuzzer
        working-directory: ${{ steps.download.outputs.download-path }}/fuzzer
        run: |
          sudo chmod +x ./osconfig-fuzzer
          ls -la ${{ steps.download.outputs.download-path }}
          mkdir /tmp/corpus
          ./osconfig-fuzzer -max_total_time=30 /tmp/corpus >osconfig-fuzzer.log 2>&1

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ inputs.target }}-crashes
          path: 'crash-*'

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: ${{ inputs.target }}-logs
          path: 'osconfig-fuzzer.log'
